DZ 4 v1
Otus-DevOps-2023-07/ivengar_infra pull request #5
Opened 2023-09-01 21:06 UTC by ivengar

# Выполнено ДЗ № 4

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - создание 3 файлов sh в корне проекта соблюдая указанные условия.

## Как запустить проект:
 - забрать файлы sh. Выполнить install_ruby.sh, install_mongodb.sh, deploy.sh

## Как проверить работоспособность:
 - http://51.250.76.218:9292/

## PR checklist
 - [ ] Выставил label YC
 - [ ] Выставил label cloud-testapp

2023-09-01 21:16 UTC, ivengar commented
Можете посмотреть? не пойму на что ругается? на директорию VPN. так она к этому дз и не относится... как поправить?

2023-09-01 21:17 UTC, ivengar commented
×  structure: Check files structure AND Check that last line has a newline symbol https://cifronomika.ru/blog/git-no-newline-at-end-of-file.html - Explanation (1 failed)
     ✔  File README.md should exist
     ✔  File install_ruby.sh should exist
     ✔  File install_ruby.sh should be allowed "execute"
     ✔  File install_ruby.sh content should match /\n\Z/
     ✔  File install_mongodb.sh should exist
     ✔  File install_mongodb.sh should be allowed "execute"
     ✔  File install_mongodb.sh content should match /\n\Z/
     ✔  File deploy.sh should exist
     ✔  File deploy.sh should be allowed "execute"
     ✔  File deploy.sh content should match /\n\Z/
     ×  Directory VPN should exist
     expected Directory VPN to exist

2023-09-02 13:36 UTC, mrgreyves requested changes
Здравствуйте!)
Нужно подмержить изменения из предыдущего дз
И все будет ок =)

2023-09-02 18:04 UTC, ivengar commented
Не очень понял. Что значит подмержить изменения из предыдущего ДЗ?
Предыдущее ДЗ я сдал, в текущем дз было написано: "Если вý вýполнили предýдущее ДЗ и закрýли PR по нему. Перенесите файлý *.ovpn
и setupvpn.sh , созданнýе в прошлом ДЗ в директориĀ VPN (желателþно с помощþĀ
командý git mv )." - Я так и сделал. что куда нужно подмержить?

2023-09-02 18:41 UTC, closed without merging